# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: false
warnings_are_errors: true
os:
  - linux
  - osx
  - win
r:
  - release
  - devel

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false

addons:
  apt:
    update: true
    packages:
      - cargo
      - libprotobuf-dev
      - libprotoc-dev
      - protobuf-compiler
      - libudunits2-dev
      - libv8-dev
      - libjq-dev
      - libgdal1-dev

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: docs
  on:
    branch: master




##########################
##########################
##########################
##########################
##########################




language: r
cache: packages

after_success:
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
